// Copyright 2014 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package core

import (
	"errors"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/core/vm"
	"github.com/ethereum/go-ethereum/event"
)

// ErrInvalidSender is returned if the transaction contains an invalid signature.
var ErrInsert = errors.New("insert errorr")

// Insert record into list order by record number
func (pool *TxPool) insertRecordWithLock(record *types.PbftRecord) error {
	lr := pool.recordList.Front()

	for {
		if lr == nil {
			pool.recordList.PushBack(record)
			return nil
		}
		r := lr.Value.(*types.PbftRecord)

		if r.Number().Cmp(record.Number()) > 0 {
			pool.recordList.InsertBefore(record, lr)
			return nil
		}

		lr = lr.Next()
	}

	return ErrInsert
}

// AddLocals enqueues a batch of transactions into the pool if they are valid,
// marking the senders as a local ones in the mean time, ensuring they go around
// the local pricing constraints.
func (pool *TxPool) AddRemoteRecords(records []*types.PbftRecord) []error {
	pool.muRecord.Lock()
	defer pool.muRecord.Unlock()

	// TODO: check record signatures
	for _, record := range records {

		pre := pool.records[record.Hash()]
		if pre == nil {
			r := types.CopyRecord(record)
			pool.records[record.Hash()] = r
			pool.insertRecordWithLock(r)
		}
	}

	return nil
}

// Pending retrieves one currently record.
// The returned record is a copy and can be freely modified by calling code.
func (pool *TxPool) PendingRecords() (*types.PbftRecord, error) {
	pool.muRecord.Lock()
	defer pool.muRecord.Unlock()
	//TODO: get the first record in the pool

	first := pool.recordList.Front()
	if first == nil {
		return nil, nil
	}
	record := pool.recordList.Remove(first).(*types.PbftRecord)

	return record, nil
}

// SubscribeNewRecordsEvent registers a subscription of NewRecordEvent and
// starts sending event to the given channel.
func (pool *TxPool) SubscribeNewRecordEvent(ch chan<- NewRecordEvent) event.Subscription {
	return pool.scope.Track(pool.recordFeed.Subscribe(ch))
}

// validateRecord checks whether a Record is valid.
func (pool *TxPool) validateRecord(record *types.PbftRecord) error {
	// TODO: check the record is signed properly
	//from, err := types.Sender(pool.signer, tx)
	//if err != nil {
	//	return ErrInvalidSender
	//}
	return nil
}

// PostChainEvents iterates over the events generated by a chain insertion and
// posts them into the event feed.
// TODO: Should not expose PostChainEvents. The chain events should be posted in WriteBlock.
func (pool *TxPool) PostNewRecordEvents(event interface{}) {
	pool.recordFeed.Send(event)
}

func (pool *TxPool) commitTransaction(tx *types.Transaction, bc *BlockChain, coinbase common.Address, gp *GasPool) (error, []*types.Log) {
	snap := pool.state.Snapshot()

	receipt, _, err := ApplyTransaction(pool.chainconfig, bc, &coinbase, gp, pool.state, pool.header, tx, &pool.header.GasUsed, vm.Config{})
	if err != nil {
		pool.state.RevertToSnapshot(snap)
		return err, nil
	}

	return nil, receipt.Logs
}
